using System;

namespace Maple2.Model.Enum;

public enum GameRankingType {
    PersonalGuildTrophy = 12,
    GuildTrophy = 14,
    PersonalTrophy = 22,
    Trophy = 24,
    DarkDescentPersonal = 31,
    DarkDescentPersonalPreviousSeason = 32,
    DarkDescent = 33,
    DarkDescentPreviousSeason = 34,
    PvpPersonal = 41,
    PvpPersonalPreviousSeason = 42,
    Pvp = 43,
    PvpPreviousSeason = 44,
    UgcPersonal = 61,
    UgcPersonalPreviousSeason = 62,
    Ugc = 63,
    UgcPreviousSeason = 64,
    RaidPersonalClear = 71,
    RaidClear = 72,
    RaidEarlyVictory = 81,
    RaidShortestTime = 91,
    ArcadePersonal = 101,
    ArcadePersonalPreviousSeason = 102,
    Arcade = 103,
    ArcadePreviousSeason = 104,
    FortressRumblePersonalSRankClear = 141,
    FortressRumbleSRankClear = 142,
    FortressRumbleEarlyVictory = 151,
    FortressRumblePersonalShortestTime = 161,
    FortressRumbleShortestTime = 162,
    ColosseumPersonal = 201,
    ColosseumPersonalPreviousSeason = 202,
    Colosseum = 203,
    ColosseumPreviousSeason = 204,
}
