namespace Maple2.Model.Enum;

public enum Instrument {
    Piano = 1,
    Misc = 2,
    Clarinet = 3,
    Harp = 4,
    Timapni = 5,
    ElectricGuitar = 6,
    Bass = 7,
    Tomtam = 8,
    Violin = 9,
    Cello = 10,
    PanFlute = 11,
    Saxophone = 12,
    Trombone = 13,
    Trumpet = 14,
    Ocarina = 15,
    AcousticBass = 16,
    Vibraphone = 17,
    ElectricPiano = 18,
    SteelDrum = 19,
    PickBassGuitar = 20,
    Oboe = 21,
    Pizzicato = 22,
    Harpsichord = 23,
    Harmonica = 24,
    Xylophone = 25,
    Recorder = 26,
    Celesta = 27,
    Cymbal = 28,
    BassDrum = 29,
    SnareDrum = 30,
    Shamisen = 31,
    Koto = 32,
    Shakuhachi = 33,
    TaikoDrum = 34,
    FretlessBass = 35,
    Marimba = 36,
    Flute = 37,
    HonkyTonkPiano = 38,
    FrenchHorn = 39,
    PipeOrgan = 40,
}
